/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoReviewTemplate: typeof import('./src/components/AutoReviewTemplate.vue')['default']
    AutoReviewTemplateList: typeof import('./src/components/AutoReviewTemplateList.vue')['default']
    AutoReviewTemplateScript: typeof import('./src/components/AutoReviewTemplateScript.vue')['default']
    CheckList: typeof import('./src/components/CheckList.vue')['default']
    CombinedImg: typeof import('./src/components/combinedImg.vue')['default']
    FilterContent: typeof import('./src/components/FilterContent.vue')['default']
    FilterContentGroup: typeof import('./src/components/FilterContentGroup.vue')['default']
    FilterContentGroupCity: typeof import('./src/components/FilterContentGroupCity.vue')['default']
    FilterContentGroupCityItem: typeof import('./src/components/FilterContentGroupCityItem.vue')['default']
    FilterContentGroupCityItemCheckbox: typeof import('./src/components/FilterContentGroupCityItemCheckbox.vue')['default']
    FilterContentShop: typeof import('./src/components/FilterContentShop.vue')['default']
    InputItem: typeof import('./src/components/inputItem.vue')['default']
    ManageCard: typeof import('./src/components/manageCard.vue')['default']
    OrderUpHistory: typeof import('./src/components/OrderUpHistory.vue')['default']
    Pcwebview: typeof import('./src/components/Pcwebview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingPopupPlanContent: typeof import('./src/components/SettingPopupPlanContent.vue')['default']
    StoreGroupTree: typeof import('./src/components/StoreGroupTree.vue')['default']
    TimeTree: typeof import('./src/components/TimeTree.vue')['default']
    Tree: typeof import('./src/components/tree.vue')['default']
  }
}
