	/** 后台任务队列类型枚举*/
	export enum JobQueueType {
		default = 0,
		store_mange = 1,
		cleanup = 3,
		high = 4,
		fdmv_pull_old_shop = 10,
		fdmv_pull_shop_foods = 11,
		fdmv_pull_actvty = 12,
		fdmv_sync_group = 13,
		fdmv_sync_foods = 14,
		fdmv_sync_actvty = 15,
		fdmv_act_to_site = 16,
		fdmg_update_name = 20,
		fdmg_update_discount = 21,
		fdmg_update_price = 22,
		fdmg_update_state = 23,
		fdmg_update_stock = 24,
		fdmg_update_image_border = 25,
		fdmg_delete_foods = 26,
		fdmg_offline_discount = 27,
		fdmg_update_minbuy = 28,
		fdmg_delete_first_image = 29,
		fdmg_recover_foods = 30,
	}
